import type { FastifyInstance } from 'fastify';
import { registerListVaultsRoute } from './list-vaults.js';
import { registerCreateVaultRoute } from './create-vault.js';
import { registerUpdateVaultRoute } from './update-vault.js';
import { registerListItemsRoute } from './items/list-items.js';
import { registerCreateItemRoute } from './items/create-item.js';
import { registerBatchCreateItemsRoute } from './items/batch-create-items.js';
import { registerUpdateItemRoute } from './items/update-item.js';
import { registerDeleteItemRoute } from './items/delete-item.js';
import { registerMoveItemRoute } from './items/move-item.js';
import { registerListVersionsRoute } from './versions/list-versions.js';
import { registerGetVersionRoute } from './versions/get-version.js';
import { registerListTrashRoute } from './trash/list-trash.js';
import { registerRestoreItemRoute } from './trash/restore-item.js';
import { registerPurgeItemRoute } from './trash/purge-item.js';
import { registerEmptyTrashRoute } from './trash/empty-trash.js';
import { registerListUserTrashRoute } from './trash/list-user-trash.js';
import { registerEmptyUserTrashRoute } from './trash/empty-user-trash.js';
import { registerCreateShareRoute } from './shares/create-share.js';
import { registerListSharesRoute } from './shares/list-shares.js';
import { registerDeleteShareRoute } from './shares/delete-share.js';
import { registerCreateFolderRoute } from './folders/create-folder.js';
import { registerListFoldersRoute } from './folders/list-folders.js';
import { registerUpdateFolderRoute } from './folders/update-folder.js';
import { registerDeleteFolderRoute } from './folders/delete-folder.js';

export function registerVaultRoutes(app: FastifyInstance): void {
  registerListVaultsRoute(app);
  registerCreateVaultRoute(app);
  registerUpdateVaultRoute(app);
  registerListItemsRoute(app);
  registerCreateItemRoute(app);
  registerBatchCreateItemsRoute(app);
  registerUpdateItemRoute(app);
  registerDeleteItemRoute(app);
  registerMoveItemRoute(app);
  registerListVersionsRoute(app);
  registerGetVersionRoute(app);
  registerListTrashRoute(app);
  registerRestoreItemRoute(app);
  registerPurgeItemRoute(app);
  registerEmptyTrashRoute(app);
  registerListUserTrashRoute(app);
  registerEmptyUserTrashRoute(app);
  registerCreateShareRoute(app);
  registerListSharesRoute(app);
  registerDeleteShareRoute(app);
  registerCreateFolderRoute(app);
  registerListFoldersRoute(app);
  registerUpdateFolderRoute(app);
  registerDeleteFolderRoute(app);
}
