/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as VaultRouteRouteImport } from './routes/_vault/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as VaultIndexRouteImport } from './routes/_vault/index'
import { Route as VaultTrashRouteImport } from './routes/_vault/trash'
import { Route as VaultSettingsRouteImport } from './routes/_vault/settings'
import { Route as VaultSessionsRouteImport } from './routes/_vault/sessions'
import { Route as VaultHealthRouteImport } from './routes/_vault/health'
import { Route as VaultAdminRouteImport } from './routes/_vault/admin'
import { Route as VaultItemIdRouteImport } from './routes/_vault/$itemId'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthRecoveryKeyRouteImport } from './routes/_auth/recovery-key'
import { Route as AuthRecoverRouteImport } from './routes/_auth/recover'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthAuthenticatorRouteImport } from './routes/_auth/authenticator'
import { Route as VaultItemsNewRouteImport } from './routes/_vault/items/new'
import { Route as VaultItemIdEditRouteImport } from './routes/_vault/$itemId_.edit'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRouteRoute = VaultRouteRouteImport.update({
  id: '/_vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultTrashRoute = VaultTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultSettingsRoute = VaultSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultSessionsRoute = VaultSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultHealthRoute = VaultHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultAdminRoute = VaultAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultItemIdRoute = VaultItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => VaultRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoveryKeyRoute = AuthRecoveryKeyRouteImport.update({
  id: '/recovery-key',
  path: '/recovery-key',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthenticatorRoute = AuthAuthenticatorRouteImport.update({
  id: '/authenticator',
  path: '/authenticator',
  getParentRoute: () => AuthRouteRoute,
} as any)
const VaultItemsNewRoute = VaultItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => VaultRouteRoute,
} as any)
const VaultItemIdEditRoute = VaultItemIdEditRouteImport.update({
  id: '/$itemId_/edit',
  path: '/$itemId/edit',
  getParentRoute: () => VaultRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof VaultIndexRoute
  '/unlock': typeof UnlockRoute
  '/authenticator': typeof AuthAuthenticatorRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/recovery-key': typeof AuthRecoveryKeyRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/$itemId': typeof VaultItemIdRoute
  '/admin': typeof VaultAdminRoute
  '/health': typeof VaultHealthRoute
  '/sessions': typeof VaultSessionsRoute
  '/settings': typeof VaultSettingsRoute
  '/trash': typeof VaultTrashRoute
  '/$itemId/edit': typeof VaultItemIdEditRoute
  '/items/new': typeof VaultItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof VaultIndexRoute
  '/unlock': typeof UnlockRoute
  '/authenticator': typeof AuthAuthenticatorRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/recovery-key': typeof AuthRecoveryKeyRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/$itemId': typeof VaultItemIdRoute
  '/admin': typeof VaultAdminRoute
  '/health': typeof VaultHealthRoute
  '/sessions': typeof VaultSessionsRoute
  '/settings': typeof VaultSettingsRoute
  '/trash': typeof VaultTrashRoute
  '/$itemId/edit': typeof VaultItemIdEditRoute
  '/items/new': typeof VaultItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_vault': typeof VaultRouteRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_auth/authenticator': typeof AuthAuthenticatorRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recover': typeof AuthRecoverRoute
  '/_auth/recovery-key': typeof AuthRecoveryKeyRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_vault/$itemId': typeof VaultItemIdRoute
  '/_vault/admin': typeof VaultAdminRoute
  '/_vault/health': typeof VaultHealthRoute
  '/_vault/sessions': typeof VaultSessionsRoute
  '/_vault/settings': typeof VaultSettingsRoute
  '/_vault/trash': typeof VaultTrashRoute
  '/_vault/': typeof VaultIndexRoute
  '/_vault/$itemId_/edit': typeof VaultItemIdEditRoute
  '/_vault/items/new': typeof VaultItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/authenticator'
    | '/login'
    | '/recover'
    | '/recovery-key'
    | '/register'
    | '/reset-password'
    | '/$itemId'
    | '/admin'
    | '/health'
    | '/sessions'
    | '/settings'
    | '/trash'
    | '/$itemId/edit'
    | '/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/authenticator'
    | '/login'
    | '/recover'
    | '/recovery-key'
    | '/register'
    | '/reset-password'
    | '/$itemId'
    | '/admin'
    | '/health'
    | '/sessions'
    | '/settings'
    | '/trash'
    | '/$itemId/edit'
    | '/items/new'
  id:
    | '__root__'
    | '/_auth'
    | '/_vault'
    | '/unlock'
    | '/_auth/authenticator'
    | '/_auth/login'
    | '/_auth/recover'
    | '/_auth/recovery-key'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_vault/$itemId'
    | '/_vault/admin'
    | '/_vault/health'
    | '/_vault/sessions'
    | '/_vault/settings'
    | '/_vault/trash'
    | '/_vault/'
    | '/_vault/$itemId_/edit'
    | '/_vault/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  VaultRouteRoute: typeof VaultRouteRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vault': {
      id: '/_vault'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vault/': {
      id: '/_vault/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/trash': {
      id: '/_vault/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof VaultTrashRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/settings': {
      id: '/_vault/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof VaultSettingsRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/sessions': {
      id: '/_vault/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof VaultSessionsRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/health': {
      id: '/_vault/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof VaultHealthRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/admin': {
      id: '/_vault/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof VaultAdminRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/$itemId': {
      id: '/_vault/$itemId'
      path: '/$itemId'
      fullPath: '/$itemId'
      preLoaderRoute: typeof VaultItemIdRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/recovery-key': {
      id: '/_auth/recovery-key'
      path: '/recovery-key'
      fullPath: '/recovery-key'
      preLoaderRoute: typeof AuthRecoveryKeyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/recover': {
      id: '/_auth/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/authenticator': {
      id: '/_auth/authenticator'
      path: '/authenticator'
      fullPath: '/authenticator'
      preLoaderRoute: typeof AuthAuthenticatorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_vault/items/new': {
      id: '/_vault/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof VaultItemsNewRouteImport
      parentRoute: typeof VaultRouteRoute
    }
    '/_vault/$itemId_/edit': {
      id: '/_vault/$itemId_/edit'
      path: '/$itemId/edit'
      fullPath: '/$itemId/edit'
      preLoaderRoute: typeof VaultItemIdEditRouteImport
      parentRoute: typeof VaultRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthenticatorRoute: typeof AuthAuthenticatorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthRecoveryKeyRoute: typeof AuthRecoveryKeyRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthenticatorRoute: AuthAuthenticatorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthRecoveryKeyRoute: AuthRecoveryKeyRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface VaultRouteRouteChildren {
  VaultItemIdRoute: typeof VaultItemIdRoute
  VaultAdminRoute: typeof VaultAdminRoute
  VaultHealthRoute: typeof VaultHealthRoute
  VaultSessionsRoute: typeof VaultSessionsRoute
  VaultSettingsRoute: typeof VaultSettingsRoute
  VaultTrashRoute: typeof VaultTrashRoute
  VaultIndexRoute: typeof VaultIndexRoute
  VaultItemIdEditRoute: typeof VaultItemIdEditRoute
  VaultItemsNewRoute: typeof VaultItemsNewRoute
}

const VaultRouteRouteChildren: VaultRouteRouteChildren = {
  VaultItemIdRoute: VaultItemIdRoute,
  VaultAdminRoute: VaultAdminRoute,
  VaultHealthRoute: VaultHealthRoute,
  VaultSessionsRoute: VaultSessionsRoute,
  VaultSettingsRoute: VaultSettingsRoute,
  VaultTrashRoute: VaultTrashRoute,
  VaultIndexRoute: VaultIndexRoute,
  VaultItemIdEditRoute: VaultItemIdEditRoute,
  VaultItemsNewRoute: VaultItemsNewRoute,
}

const VaultRouteRouteWithChildren = VaultRouteRoute._addFileChildren(
  VaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  VaultRouteRoute: VaultRouteRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
